---
galaxy_info:
  description: "Install and configure Grafana on kubernetes"
  role_name: "loki"
  author: "Cl√©ment Hubert"

  license: "MLP2"

  min_ansible_version: "2.1"

  galaxy_tags:
    - "kubernetes"
    - "loki"
    - "observability"
    - "logs"

dependencies: []
